### ISSUE TITLE
New Core 2.0 & Rotation

### ISSUE THREAD

**Issue by ghost** [Null-Signal-Games/netrunnerdb#136]
would be nice if Rotation & Core 2.0 would be supported to check deck legality.
Currently it's hard to do post rotation decks, you need to deactivate the data packs + world champ decks.

But with Core 2.0 this becomes nearly impossible.

**Comment by eljenso** [comment]
According to his tweet, Alsciende is currently working on it:  
https://twitter.com/alsciende/status/907523030649376768

**Comment by zanlib0** [comment]
I'm not entirely sure but I feel that the Core 2.0 cards were implemented just by adding new entries to the card database with changed set numbers. This might prove to be an issue later down the line and it already causes problems such as duplicates in the [faction page](https://netrunnerdb.com/en/faction/haas-bioroid) (Stronger Together is shown twice).

**Comment by eljenso** [comment]
Yes, they were added as copies, see the [PR](https://github.com/Alsciende/netrunner-cards-json/pull/251).

I hope the current implementation is just a quick fix. There must be a more elegant way to implement this, without duplicates.

**Comment by Saintis** [comment]
Most future proof would probably be to add versioning to cards. Would be useful if cards from previous cycles are reprinted with the same name.

**Comment by eljenso** [comment]
This discussion should be done in [Alsciende/netrunner-cards-json](https://github.com/Alsciende/netrunner-cards-json), I opened an issue for this purpose.

**Comment by gereons** [comment]
If you look at the PR closely, you will find that I initially attempted to preserve the card codes. As far as I understood @Alsciende it is currently not possible for him to remove the one-to-one mapping from packs to cards and vice versa without basically rewriting NRDB, and that is the reason for the assignment of new codes.

**Comment by ghost** [comment]
and I assume this is why the world champ decks have been removed, as they would cause issues. At the end currently there is no implementation for this when I need to remove packs I have. I accept, understand and I'm happy with it and I know it's not his job to do it, but I think it's not a solution, there should be a check like it's for the MWL.

**Comment by alsciende** [comment]
The core of the issue is that in the current model, 1 card belongs to 1 pack and 1 pack only. So creating a new core2 with its cards was the best short-term solution. New cards had to have new codes, since "code" is the functional primary key of the cards. 

I removed the WC because they caused more harm than good. People often forget to uncheck them, and since they contain cards from the core1, it would have turned the WC decks from a minor annoyance to a major headache.

Long-term, the solution is obviously to have cards separated from packs, and add a n-to-n relation between them, so that a card can be related to several packs. The rumors around Core 2.0 foretold me that this would be needed someday, and I built the new FiveRingsDB with that in mind (you can check https://github.com/Alsciende/fiveringsdb-data). For the record, this solution makes things slightly more complicated, but it has already proven to be worth it because of the promo cards.

Now, the thing is, I won't "backport" this to NetrunnerDB. The code of NetrunnerDB is old, it hurts me everytime I have to touch it. It was my first big project, I want to slap past-me all the time ; if you're a coder you know the feeling. Also the software stack is old. No js framework. PHP5. So, if I can muster the energy, the plan is to re-code NetrunnerDB on top of FiveRingsDB, which will solve the card-pack issue.

That being said, if someone wants to submit a PR with a clean separation between cards and packs, I'll support it.

**Comment by NoahTheDuke** [comment]
Welp, I took it upon myself to actually attempt the change-over. Come let me know what y'all think!

**Comment by NoahTheDuke** [comment]
All done!
