### ISSUE TITLE
Migrate card reviews to core set

### ISSUE THREAD

**Issue by playground999** [Null-Signal-Games/netrunnerdb#143]
Would it be possible to have the cards in the revised set show the reviews from the original cycle? Its hard building a deck to show rotation because now I can't see any reviews.

**Comment by ghost** [comment]
I think that the reviews might not be on par with the actual card pool! As they take into account other cards that are not legal any more like deja vu or Account Siphon.
So I think it would be best to link the new version of the card to the old one, so you can find the old review.

**Comment by x3N1GM4x** [comment]
Because of the way cards which appear in multiple core sets are currently implemented (as entirely separate cards) and the point raised by @5N00P1 above, it's not necessarily desirable to show all reviews from all releases of the same card.
However, in "the future", it is planned to refactor the underlying DB so cards which feature in multiple cores (or have alt arts for example) exist as just one card with multiple sets of properties, so I expect it will then be possible to browse through the versions of a particular card, seeing the appropriate reviews as you do so.

**Comment by ghost** [comment]
it might also be nice to link the other reviews or however it's implemented.
e.g.
- Project Beal from xxx (3 reviews) as a link
- Project Beal from Revised Core

**Comment by NoahTheDuke** [comment]
Done!
