### ISSUE TITLE
Card suggestions not being shown

### ISSUE THREAD

**Issue by dummiesday** [Null-Signal-Games/netrunnerdb#217]
Card suggestions are not shown on any of the decks I create. The tab itself is visible but no suggestions are shown.

I've experienced this issue on Windows 10 64bit, both in the latest version of Chrome and Edge.

Please let me know if you need any additional information.

![bug suggestions](https://user-images.githubusercontent.com/14167840/37873380-c5aaf1c0-3013-11e8-846f-906a218ab5b4.JPG)

**Comment by dummiesday** [comment]
Still experiencing the issue. I've tried clearing my cache, deleting cookies, using Internet Explorer and Mozilla, deactivating AdBlock.... Not sure what else I can do.

The console on Chrome gives me this information:

version: 65
chrome-extension://bbmegnmpleoagolcnjnejdacakedpcgd/Plugin/Ex.js:1068 ex.js page check url
chrome-extension://bbmegnmpleoagolcnjnejdacakedpcgd/Plugin/Ex.js:1074 undefined
nrdb.data.js:58 all db successfully reloaded from storage
/corp.json Failed to load resource: the server responded with a status of 404 (Not Found)
nrdb.suggestions.js:26 [2018-04-15 18:20:13] Error on /corp.json error Not Found

It seems something related to the suggestions is not loading properly. Does this help?

Thanks!

**Comment by x3N1GM4x** [comment]
So the issue seems to be here:

https://github.com/Alsciende/netrunnerdb/blob/a83827df107ea4d0b7e3e5e9430497a9281f7edb/web/js/nrdb.suggestions.js#L9-L30

I believe L10 is where `/corp.json` is being defined (`'/'+side+'.json'`) and then this is resulting in an error being thrown and outputted on L26. I don't see any `corp.json` in this repo or [netrunner-cards-json](https://github.com/Alsciende/netrunner-cards-json).

I don't know enough about exactly how this works to be able to help much more, but hopefully this info will be useful to someone else around here.

**Comment by natthew** [comment]
I think the only thing that needs to be done to make this work is to run the SuggestionsCommand for the runner and corp sides.

**Comment by x3N1GM4x** [comment]
@dummiesday - are you still experiencing this issue, or has it now been resolved? I cannot reproduce myself.

**Comment by NoahTheDuke** [comment]
I can't reproduce this either. Closing for now, especially with changes coming in #328.
