### ISSUE TITLE
Need to re-login when deleting deck

### ISSUE THREAD

**Issue by tf42src** [Null-Signal-Games/netrunnerdb#247]
Is this a feature? I am logged in, I can browse my decks etc. but deleting a deck prompts me with the login screen again.

**Comment by x3N1GM4x** [comment]
It's not intentional as far as I'm aware, and I'm also unable to reproduce it either in Production or on my local instance. Have you always been re-prompted for credentials when deleting a deck, or has this only started happening recently?

Do you still have the problem if you log out of NRDB, log back in and immediately attempt to delete a deck once logged in? I have experienced my session timing out while being sat on deckbuilder or some other screen for too long.

**Comment by tf42src** [comment]
Started a few months ago I think. Definitely shouldn't have hit session timeout as I (sometimes) just had logged in before.

**Comment by gereons** [comment]
Can confirm, this has happened to me a few times as well.

**Comment by ghost** [comment]
Same for me, it's annoying!
I think it has to do with the same issue like writing reviews for cards #252 , but this is only a feeling!
And I have the same using ABR, whenever I want to claim I have to relogin.

**Comment by gereons** [comment]
Just happened to me again, which prompted some digging. AFAICT, this is not a bug but rather an intentional feature. 

Symphony apparently distingushes between `IS_AUTHENTICATED_FULLY` and `IS_AUTHENTICATED_REMEMBERED` login states - you're "fully" authenticated when you've just entered your credentials during this session, and "remembered" when you're logged in because you have the correct cookies. Now, the methods responsible for deleting decks (`BuilderController::deleteAction` and `BuilderController::deleteListAction`) are marked `@IsGranted("IS_AUTHENTICATED_FULLY")`, so you're forced to re-login.

**Comment by NoahTheDuke** [comment]
That’s super interesting! Sounds like a protection against cookie stealing or hijacking.

**Comment by gereons** [comment]
Most likey that's the intention. 

The UX is still crappy as hell IMO; if a site does something like this it should a) explain this to me, and (more importantly) b) don't make me f****ing re-do all my input, in this case re-select all the decks I'd like to remove.

**Comment by ghost** [comment]
I would not call it an enhancement! When looking into the write card review, the site terminates with an error and all your input is lost! I wrote an article 3x!
So I think something should happen around it, as a noob has no chance to see where it's coming from and might be frustrated by the site!
So a chance to login would be very very welcome, but losing content people are providing is not something where we need an enhancement.

**Comment by gereons** [comment]
Totally agree with @5N00P1. I suggest that we change all of those IS_AUTHENTICATED_FULLY markers to IS_AUTHENTICATED_REMEMBERED to eliminate this for now - PR is incoming.

**Comment by x3N1GM4x** [comment]
My bad @5N00P1 , can't even remember why I flagged this as an enhancement now, but not to worry as @gereons has implemented a fix now anyway! 🎉

**Comment by NoahTheDuke** [comment]
It's an enhancement to remove change from the old, bad UX to the new, smooth UX.
