### ISSUE TITLE
Images and decklists not loading

### ISSUE THREAD

**Issue by matthiasfabry** [Null-Signal-Games/netrunnerdb#248]
I use Firefox 62.0.03 64bit and the images and decklists are not loading. Using the inspector reveals that the sources of those images and cards could not be found (see picture attached)
![nrdbissue](https://user-images.githubusercontent.com/17302115/46904789-0668ca00-ceea-11e8-84c3-cee83022893e.png)

**Comment by x3N1GM4x** [comment]
I can't reproduce this on the current version of FF (63.0.3): 
![image](https://user-images.githubusercontent.com/10621139/49652365-cd506000-fa29-11e8-9c77-6a45c7e161ae.png)
Have you tried upgrading to the latest version since logging this issue? Is there anything in the Console output which suggests what the issue might be?

**Comment by matthiasfabry** [comment]
it seems that disabling content blocking did the trick. Thanks nevertheless for trying to reproduce.
