### ISSUE TITLE
Support for seeing the alternate art and full bleed versions of cards

### ISSUE THREAD

**Issue by dickoff** [Null-Signal-Games/netrunnerdb#25]
NRDB should be a resource for finding information about the alt art/full bleed\* versions of cards. I'm not sure what the best way to support this is, but one should be able to search and find information about them on NRDB. 

Some data about an alt art that would differ from the original:
- Illustrator of an alt art is often different than the illustrator of the original.
- Alt arts usually have an event that they are received at (e.g. a certain GNK kit or big tournament)

Full bleed cards are likely to be exactly the same as the original but it would be nice to be able to see the image on NRDB.

*Full bleed cards: Lotus field is a released example. The world championship decks will be the next big influx of these.

**Comment by alsciende** [comment]
Sorry, I'm not interested in supporting alt-art cards anymore.

**Comment by dickoff** [comment]
Would you accept a pull request or do you not want this functionality in NRDB?

**Comment by alsciende** [comment]
I had it previously, but I removed it at the start of 2015 (https://bitbucket.org/alsciende/nrdb/commits/6972980a71abdbb477042f125c8b5b353cdc758c). It's too much hassle, to support the alt-arts in the code and to keep the data up-to-date.

What could be done is... Adding a property to each card to indicate if it has a full art version, and if so, where does it come from: `Card.alternate string(255) nullable`. Display the text of that property on the page of the card (`display_zoom`). That text is a link to the image of the alternate. The filepath of the alternate card image is fixed: it's always the card code suffixed with `_alt`, e.g. `01001_alt.png` for alt Noise.

Caveats: no additional info on the alt-art (no illustrator), no way to have more than 1 alt-art for each card.

Going further, the text could trigger the replacement of the regular card image by its alternate, instead of being a link to it. Also, the alternate text could be displayed in a tooltip on `display_card` (View as full cards when multiple cards).
