### ISSUE TITLE
Ika Review

### ISSUE THREAD

**Issue by Havvy86** [Null-Signal-Games/netrunnerdb#250]
It appears you cannot post a review for Ika card. My username is Havvy and I believe I have the correct rights to post the review?

**Comment by x3N1GM4x** [comment]
Have you been able to post reviews on other cards since you noticed this? Do you get any specific error message or behaviour you can describe (or event better, capture in screenshots) when you attempt to post the review?

There is also one review on the live site for this card, so it's not a universal inability to post reviews for this card.

I'm not able to reproduce this issue on my local instance, so we're going to need to try and gather some more information to be able to help.

**Comment by Havvy86** [comment]
Hi there!

(By any chance, are you Ian Witt? I’m in the tournament group!).

I’ve tried this again today and got the following error:

Reviews
An error occured while posting your review (OK). Reload the page and try again.
I noticed there are reviews on this card now, so I suspect it might be just me?

Thanks

Ian

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by x3N1GM4x** [comment]
Yes, that's me, hi!

It certainly sounds like something local to your machine or account. Perhaps you could take a look at your web browser's console when you get that error to see if any further detail is being recorded there?

Details on how to do this if you're not aware will vary depending on your browser, there's a summary for the major browsers [here](https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors). Alternatively, just google "[browser_name] view console" or similar.

**Comment by ghost** [comment]
See #252 as I assume it's the same and as there I think this is linked to #247

**Comment by Havvy86** [comment]
That looks identical with the error message.

Word count is 243 though for my review!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by x3N1GM4x** [comment]
Closing as should be resolved by #285.
@Havvy86 - let us know if you're still having this problem.
