### ISSUE TITLE
[Suggestion] add MWL info to deck/decklist APIs

### ISSUE THREAD

**Issue by gereons** [Null-Signal-Games/netrunnerdb#28]
It would be great to get a deck's MWL info as part of the API. Maybe add an optional property "mwl_version" with values "1.0" or "1.1"? (unset or null would mean "Casual" in this case)

Related to this: wouldn't it be better to call the differenct MWL versions by their version number ("MWL v1.0" and "MWL v1.1") instead of by the name of the document that introduced them?

**Comment by alsciende** [comment]
I can't find any version number for the MWL in FFG's documentation. Where did you find it?

A (private) deck doesn't have any MWL info. It's calculated on the fly. Only (public) decklists have MWL info. I don't think you use decklists anyway.

**Comment by gereons** [comment]
The MWL versions are right there in the tournament regulations, on page 9 of the latest version, where it says "Appendix A, NAPD Most Wanted List, Version 1.1 / Effective 8.1.2016"

Aren't you storing the chosen value of the "Legality" dropdown along with each deck? That's what I was hoping to get at.

**Comment by alsciende** [comment]
I'll be damned. There's no version number in the "text version" of the TR document...

It's so weird to call it v1.1. Why not v2?

**Comment by alsciende** [comment]
Actually yes, I'm storing the chosen value of the "Legality" dropdown. Sorry for the wrong info. I can send the internal id (reference to https://netrunnerdb.com/api/2.0/public/mwl), but it'd be better to send a code I guess. Since the MWLs are version-numbered, we could use this as code. `NAPD_MWL_1.0`, `NAPD_MWL_1.1` would be the current official MWL. Non-official MWL would start with a string different from `NAPD_MWL`, like `ANRPC_GLC_1.0`. What do you think?

**Comment by gereons** [comment]
Any unique identifier will do, so `NAPD_MWL_1.0` is fine.
