### ISSUE TITLE
New ABR links shown even where no profile exists

### ISSUE THREAD

**Issue by x3N1GM4x** [Null-Signal-Games/netrunnerdb#399]
All user pages now have a link to ABR thanks to #397 , even where that user does not exist on ABR, so in those cases the URL just 404s.

Could we pre-check somehow and only show the link where there's a valid ABR profile on the other end?

**Comment by plural** [comment]
We don't have a way right now to know if a given NRDB user has ever logged in to NRDB.  We do know that since ABR only uses NRDB for auth, that we'll have the right URL.

I'll look at adding a note to the profile page about this.  I don't know that it is worth doing a server-side HTTP request over to ABR just to save that link from pointing to a 404.
