### ISSUE TITLE
OAuth access

### ISSUE THREAD

**Issue by North101** [Null-Signal-Games/netrunnerdb#547]
Hi,

I've created a Netrunner Deckbuilding app and I want to have access to the OAuth API.
https://netrunnerdb.com/api/2.0/doc says "please send me an email describing your project" but I can't find any email on the site so I hope you don't mind me posting it here instead.

Description: Netrunner Deckbuilding App
Application Name: NetDeck
Application Website: https://github.com/north101/netdeck
Redirect Uri: uk.co.north101.flutter.netdeck://oauth2callback

**Comment by North101** [comment]
![Screenshot_20210611-235528](https://user-images.githubusercontent.com/1031451/121755998-a00c2d80-cb10-11eb-8799-2d5f47cb1ead.jpg)
Also: is having this ok in the app?

**Comment by North101** [comment]
@plural?

**Comment by plural** [comment]
hey there! sorry i am just now getting to this.

i can take care of this for you, but i need a way to get the keys to you securely.  Can you contact me on slack or something so we can figure out a way to get the keys to you?  I'll make a form or something to collect OAuth requests since "send me an email" clearly isn't the right thing we should have on the site.  :D

**Comment by North101** [comment]
No prob. For some reason I thought github had a private messaging system but seems I'm mistaken.
Is it the stimhack slack?
